"""empty message

Revision ID: 142eb413e087
Revises: 8762dea2bb2a
Create Date: 2024-03-18 16:49:33.280556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142eb413e087'
down_revision = '8762dea2bb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
