"""empty message

Revision ID: 54bc01c08ba8
Revises: 2170e68846da
Create Date: 2024-04-14 14:18:57.623006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54bc01c08ba8'
down_revision = '2170e68846da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=60), nullable=True))
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    # ### end Alembic commands ###
